sudo: required
services:
- docker
language: bash
script:
- git clone https://github.com/jwilder/nginx-proxy nginx-proxy
- cd ./nginx-proxy
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t forkpushbot/my-test-repo .
# test image
- docker run forkpushbot/my-test-repo uname -a
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKERHUB_USER" -p="$DOCKERHUB_PASS"
    TAG=latest
    docker tag forkpushbot/my-test-repo forkpushbot/my-test-repo:$TAG
    docker push forkpushbot/my-test-repo:$TAG
    docker push forkpushbot/my-test-repo
  fi